### PR TITLE
Update pyzoSourceStructure.py

### PR DESCRIPTION
**Pull request by Ahmed-E-86**
These colors are better than the other ones.

### CODE REVIEW

**Comment by Ahmed-E-86** [comment]
This PR solves this issue -> https://github.com/pyzo/pyzo/issues/812

**Comment by almarklein** [comment]
I don't see how this fixed #812, does it not still have a light background? Could you show a screenshot?

**Comment by Ahmed-E-86** [comment]
It is the same background, but with brighter colors.

Actually they are the same colors that you commented before, I just uncommented them, and they look better with dark background, and I think that they will be fine with light background as well.

Screenshot_20220907_152123

**Comment by almarklein** [comment]
Now I see! The text is barely visible, and the lighter background of the top item is because it is selected.

> I think that they will be fine with light background as well.

Well, the colors currently match the default syntax highlighting, so this change would introduce a discrepancy. The best solution would be if the source structure simply took the colors from the syntax theme. This is a bit more work though ...

**Comment by almarklein** [comment]
Supersceded by #828

**Pull request closed without merging**
