### PR TITLE
Qt6 support

### LINKED ISSUE #742: PySide6 support
hello,

Would it be possible to get an easy PySide6 support ?
There is a compatibility fix merged for pyqtgraph https://github.com/pyqtgraph/pyqtgraph/pull/1495
There is an effort of compatibility fix for QtPy https://github.com/spyder-ide/qtpy/pull/225

### PR DESCRIPTION
**Pull request by almarklein**
Closes #742

### CODE REVIEW

**Comment by almarklein** [comment]
I'm just going to merge, because I will change CI to use GH actions anyway.

**Comment by stonebig** [comment]
Hoi,

On Windows/PyQt-6-6.2.2, it seems Pyzo-master of 2021-12-21-1800pm is not succeedding to fully start, on Windows
image

on the Dos launching windows, I get this
image

**Comment by almarklein** [comment]
I also renamed `master` to `main` yesterday. If you did not mean `main` then you might be slightly out of date :)

**Comment by almarklein** [comment]
In CI we now actually run Pyzo and close it after a few secs. With a bit more love, that check could also check for errors like this.

**Comment by almarklein** [comment]
Ah, I now see that you created #779. Great! Will repeat my response there :)

**Comment by stonebig** [comment]
oups ! sorry.

**Comment by almarklein** [comment]
No problem. Good to track this in a new issue :)

**Pull request merged**
