### PR TITLE
Attempt at hiding methods

### PR DESCRIPTION
**Pull request by fstengel**
By piggybacking the "hide function" menu item. I use a dictionnary to
map what I want to hide to the relevant menu item. A bit
overengineered, but can be extended.

### CODE REVIEW

**Comment by almarklein** [comment]
Am I correct that now it would hide methods, but not functions anymore?

**Comment by fstengel** [comment]
No, it does hide both functions and methods at once or none. For instance, if in the dictionary (*typeTranslation*) one were to find the entry "codeobject": "function", then when selecting "hide functions" one would hide as well items of type "codeobject". what I do is map some object types to the types known to the filtering mechanism.

Currently my (long) code simulates something of the sort:
```python
if kind=="method":
    kind = "function"
```
The only advantge is that it is extensible, with the caveat of being a tad overengineered.

**Comment by almarklein** [comment]
Ah, I see; I read it the wrong way :)

Great, its extensible, but I don't think it add too much complexity in doing so, so let's get this in!

**Comment by almarklein** [comment]
Thanks!

**Pull request merged**
