### PR TITLE
Allow files with spaces to run as script in IPython

### LINKED ISSUE #509: Pyzo 4.4.1 with IPython - cannot run file as script when path contains spaces
Here is the path of a test file I am using, note that it contains a blank space:
/Path/To/My documents/Test.py

With Pyzo 4.3.1 using IPython 5.3.0 I am able to launch this file as a script. The shell says

`Running script: "/Path/To/My documents/Test.py"`

and the script runs normally.

Now with Pyzo 4.4.1 using IPython 5.3.0 the shell says
```
%run -i /Path/To/My documents/Test.py
File `'/Path/To/My.py'` not found.
```

Obviously something has changed in the script invocation mechanism, and there is a pair of quotes missing here around the file path.

### PR DESCRIPTION
**Pull request by hudcap**

### CODE REVIEW

**Comment by almarklein** [comment]
Thanks for this!

I'm uncertain whether the use of double-quotes works on both Linux and Windows. What OS are you on yourself?

**Comment by hudcap** [comment]
Oh, sorry - I'm on Windows.

**Comment by almarklein** [comment]
Ok, I'll spin up a Linux VM to try this out when I have some free cycles.

**Comment by almarklein** [comment]
Thanks! I just confirmed that it fixes things for Linux too.

**Pull request merged**
