### PR TITLE
Automatic insertion of colons after class, def, if...

### PR DESCRIPTION
**Pull request by kelsa-pi**

### CODE REVIEW

**Comment by almarklein** [comment]
You're on a roll! Sorry, I have not been able to look at it yet. I have EuroPython coming up. I'll try taking a look soon.

**Comment by kelsa-pi** [comment]
Please ignore/delete last commit "Sort source structure" , this is separate PR. Hm, I am totally confused about how this is supposed to work :(

**Comment by almarklein** [comment]
Yes, git can be confusing :)

I'd recommend using branches. If you work on one thing at a time, using the master branch works fine, but when you work on multiple things at the same time, things get in each-others way. So what I usually do in projects is do:

```
# Update
git checkout master  # in case you were not at the master branch already
git pull upstream  # to get the latest version of the official repo
# Prepare 
git checkout -b autocolons  # create a new branch names "autocolons", and switch to it
# Do work
git commit -am "bla"  # this commit is now on this separate branch
git push origin autocolons  # push the branch to your repo
# After your PR is merged
git checkout master
git pull upstream
```

You may need to setup upstream like so:
```
git remote add upstream https://github.com/pyzo/pyzo
```

**Comment by almarklein** [comment]
And for now, we need to get that last commit away:
```
git checkout HEAD~1
git checkout -b autocolons
git push origin autocolons
# ... make a new PR
```

**Comment by kelsa-pi** [comment]
Thanks, I will try that.

**Comment by almarklein** [comment]
Or, just copy the code and make a new PR from that :)

**Pull request closed without merging**
