### PR TITLE
Hide default vars in workspace

### PR DESCRIPTION
**Pull request by ysalmon**
While translating the workspace into French, I thought it would be interesting to give the user (or rather the site administrator) to hide the variables that the IPython shell creates upon startup (``In``, ``Out``, etc.).

I also added a text message to be displayed in place of the variable list when this list is empty.

This PR is on top of #616.

### CODE REVIEW

**Comment by almarklein** [comment]
Superseded by #625

**Comment by almarklein** [comment]
(somehow this still shows all the commit from previous pr's, making it hard to review)

**Comment by ysalmon** [comment]
Ah, the PR reference point does not move when master is updated ?

I stopped creating branches on top of each other, restarting from master instead, to avoid too complicated PRs. This has the drawback of forcing a delay in translating, as the translation files are either difficult or impossible to merge in case of a conflict.

**Comment by almarklein** [comment]
Normally it works, I think. But there was a tiny merge conflict with the translation PR. Perhaps that prevented Github from "dropping" existing commits in this PR ...

**Pull request closed without merging**
